# ===================================================================
#                       Shared Configuration
# This section contains parameters common to all models and experiments.
# ===================================================================
seed: 42
outputDir: '/path/to/output_directory'
datasetPath: '/path/to/dataset'
device: 'cuda:1'

# data processing
data:
  whiteNoiseSD: 0.8
  constantOffsetSD: 0.2
  gaussianSmoothWidth: 2.0
  strideLen: 4
  kernelLen: 32
  restricted_days: []
  maxDay: null # Set to null if not doing held out days testing
  nDays: 24
  batchSize: 64
  num_masks: 20 
  max_mask_pct: 0.075
  
# optimization
optimizer:
  AdamW: false
  lrStart: 0.02
  lrEnd: 0.02
  l2_decay: 1.0e-5
  beta1: 0.9
  beta2: 0.999
  learning_scheduler: 'none'
  milestones: [150]
  gamma: 0.1
  n_epochs: 73
  dropout: 0.35
  input_dropout: 0.0

# ===================================================================
#                    Model-Specific Configurations
# Each sub-section defines the architecture for a different model.
# ===================================================================
model:
  # --- GRU Model Arguments ---
  gru:
    name: 'GRU'
    nInputFeatures: 256
    nClasses: 40
    nUnits: 1024
    nLayers: 5
    bidirectional: false
    strideLen: 4
    kernelLen: 14


  # --- Transformer Model Arguments ---
  transformer:
    name: 'Transformer'
    nInputFeatures: 256 # Often the same as d_model
    nClasses: 40
    # --- PASTE YOUR TRANSFORMER ARGS BELOW ---
    d_model: 512        # Example: Model dimension
    n_heads: 8          # Example: Number of attention heads
    dim_feedforward: 2048 # Example: Dimension of feedforward network
    patch_size: (5, 256)
    depth: 5 





  