outputDir: /data2/brain2text/b2t_24/outputs/
manifest_paths:
- /data2/brain2text/b2t_24/trial_level_data/manifest.json
participant_suffixes:
- _24
seeds:
- 0
- 1
- 2
- 3
- 4
- 5 
- 6
- 7
- 8 
- 9 
evaluate_wer: false
evaluate_every_n_epochs: 1
modelName: gru_b2t_24_baseline
modelType: gru
optimizer: Adam
learning_rate: 0.02
beta1: 0.9
beta2: 0.999
eps: 0.1
learning_scheduler: none
n_epochs: 73
milestones:
- 150
gamma: 0.1
lr_scaling_factor: 1.0
learning_rate_decay_steps: 250
learning_rate_warmup_steps: 0
batchSize: 64
nClasses: 40
normalize_ctc_len: true
load_pretrained_model: ''
grad_norm_clip_value: -1
early_stopping_enabled: false
early_stopping_checkpoint: 500
early_stopping_wer_threshold: 1
early_stopping_per_threshold: 1
early_stopping_no_improvement: 50
num_masks: 0
max_mask_pct: 0.0
whiteNoiseSD: 0.8
constantOffsetSD: 0.2
gaussianSmoothWidth: 2.0
smooth_kernel_size: 20
random_cut: 0
use_amp: true
l2_decay: 1.0e-05
input_dropout: 0.0
dropout: 0.40
model:
  gru:
    name: GRU
    year: '2024'
    nInputFeatures: 256
    nClasses: 40
    nUnits: 1024
    nLayers: 5
    bidirectional: true
    strideLen: 4
    kernelLen: 32
    nDays: 24
    shared_input: false
  transformer:
    name: Transformer
    features_list:
    - 512
    samples_per_patch: 4
    n_heads: 6
    mlp_dim_ratio: 4
    dim_head: 64
    depth: 5
    chunked_attention:
      chunkwise_prob: 0.5
      chunk_size_min: 1
      chunk_size_max: .inf
      left_constrain_prob: 1.0
      context_sec_min: 5
      context_sec_max: 20
      timestep_duration_sec: 0.08
      eval:
        chunk_size: 1
        context_sec: 20
wandb:
  project: nejm-brain-to-text
  entity: lionelhu926-ucla
