outputDir: /data2/brain2text/b2t_25/outputs/
manifest_paths:
- /data2/brain2text/b2t_25/trial_level_data/manifest.json
participant_suffixes:
- _25
seeds:
- 0
- 1
- 2
- 3
- 4
evaluate_every_n_epochs: 1
modelName: gru_b2t_25_baseline_brainaudio
modelType: gru
optimizer: AdamW
learning_rate: 0.005
beta1: 0.9
beta2: 0.999
eps: 0.1
learning_scheduler: cosine
scheduler_step: per_batch
n_epochs: 950
milestones:
- 300
gamma: 0.1
lr_scaling_factor: 0.02
learning_rate_decay_steps: 120000 # batch counting for 25
learning_rate_warmup_steps: 1000
batchSize: 64
nClasses: 40
load_pretrained_model: ''
grad_norm_clip_value: 10
early_stopping_enabled: false
early_stopping_no_improvement: 50
normalize_ctc_len: false
num_masks: 0
max_mask_pct: 0
whiteNoiseSD: 1.0
constantOffsetSD: 0.2
gaussianSmoothWidth: 2.0
smooth_kernel_size: 100
random_cut: 3
use_amp: true
l2_decay: 0.001
input_dropout: 0.2
dropout: 0.4
model:
  gru:
    name: GRU
    nInputFeatures: 512
    nClasses: 40
    nUnits: 768
    nLayers: 5
    bidirectional: false
    strideLen: 4
    kernelLen: 14
    nDays: 45
    shared_input: false
  transformer:
    name: Transformer
    features_list:
    - 512
    samples_per_patch: 4
    n_heads: 6
    mlp_dim_ratio: 4
    dim_head: 64
    depth: 5
    chunked_attention:
      chunkwise_prob: 0.5
      chunk_size_min: 1
      chunk_size_max: .inf
      left_constrain_prob: 1.0
      context_sec_min: 5
      context_sec_max: 20
      timestep_duration_sec: 0.08
      eval:
        chunk_size: 1
        context_sec: 20
wandb:
  project: nejm-brain-to-text
  entity: lionelhu926-ucla
