outputDir: /home/ebrahim/data2/brain2text/b2t_25/outputs/
manifest_paths:
- /home/ebrahim/data2/brain2text/b2t_25/trial_level_data/manifest.json
participant_suffixes:
- _25
seeds:
- 7
evaluate_wer: false
evaluate_every_n_epochs: 1
modelName: neurips_b2t_25_causal_transformer_v4
modelType: transformer
optimizer: AdamW
learning_rate: 0.002
beta1: 0.9
beta2: 0.999
eps: 1.0e-08
learning_scheduler: multistep
n_epochs: 500
milestones:
- 300
gamma: 0.1
lr_scaling_factor: 0.1
learning_rate_decay_steps: 500
learning_rate_warmup_steps: 10
batchSize: 64
nClasses: 40
load_pretrained_model: ''
grad_norm_clip_value: 100
early_stopping_enabled: false
early_stopping_checkpoint: 951
early_stopping_wer_threshold: 1
early_stopping_per_threshold: 1
early_stopping_no_improvement: 95
num_masks: 20
max_mask_pct: 0.05
whiteNoiseSD: 0.2
constantOffsetSD: 0.05
gaussianSmoothWidth: 2.0
smooth_kernel_size: 20
random_cut: 0
use_amp: true
l2_decay: 1.0e-05
input_dropout: 0.2
dropout: 0.35
acoustic_scale: 0.6
lm_weight: 2.0
word_score: 0.1
beam_size: 30
interctc:
  enable_interctc: falsttmue
  alpha: 0.25
  inter_ctc_per_layers: 3
model:
  gru:
    name: GRU
    year: '2024'
    nInputFeatures: 256
    nClasses: 40
    nUnits: 1024
    nLayers: 5
    bidirectional: true
    strideLen: 4
    kernelLen: 4
    nDays: 24
  transformer:
    name: Transformer
    features_list:
    - 512
    samples_per_patch: 4
    n_heads: 6
    mlp_dim_ratio: 4
    dim_head: 64
    depth: 5
    chunked_attention:
      chunkwise_prob: 1
      chunk_size_min: 1
      chunk_size_max: 1
      left_constrain_prob: 1
      context_sec_min: 5
      context_sec_max: 20
      timestep_duration_sec: 0.08
      eval:
        chunk_size: 1
        context_sec: 20
wandb:
  project: nejm-brain-to-text
  entity: lionelhu926-ucla
