outputDir: /data2/brain2text/b2t_24/outputs/
datasetPath:
- /data2/brain2text/b2t_24/brain2text24_log.pkl
device: cuda:0
evaluate_wer: true
evaluate_every_n_epochs: 5
modelName: tm_transformer_b2t24_log_dynchunk_small_v3
modelType: transformer
optimizer: AdamW
learning_rate: 0.001
beta1: 0.9
beta2: 0.999
eps: 1.0e-08
learning_scheduler: cosine
n_epochs: 951
milestones:
- 400
gamma: None
learning_rate_min: 0.0001
learning_rate_decay_steps: 120000
learning_rate_warmup_steps: 1000
batchSize: 64
nClasses: 40
seed: 0
load_pretrained_model: ''
grad_norm_clip_value: 10
num_masks: 20
max_mask_pct: 0.075
whiteNoiseSD: 0.2
constantOffsetSD: 0.05
gaussianSmoothWidth: 2.0
smooth_kernel_size: 20
random_cut: 0
use_amp: true
l2_decay: 1.0e-05
input_dropout: 0.2
dropout: 0.35
acoustic_scale: 0.8
lm_weight: 2.0
word_score: 0.1
beam_size: 30
model:
  gru:
    name: GRU
    year: '2024'
    nInputFeatures: 256
    nClasses: 40
    nUnits: 1024
    nLayers: 5
    bidirectional: true
    strideLen: 4
    kernelLen: 4
    nDays: 24
  transformer:
    name: Transformer
    features_list:
    - 256
    samples_per_patch: 5
    d_model: 384
    n_heads: 6
    mlp_dim_ratio: 4
    dim_head: 64
    depth: 5
    chunked_attention:
      chunkwise_prob: 0.5
      chunk_size_min: 1
      chunk_size_max: 5
      left_constrain_prob: 0.5
      context_chunks_min: 30
      context_chunks_max: 50
      seed: 1
      eval:
        chunk_size: .inf
        context_chunks: null
wandb:
  project: nejm-brain-to-text
  entity: lionelhu926-ucla
